owenvoke/skeleton-php

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

This updates the new format of issue templates as defined here:
https://help.github.com/en/articles/about-issue-and-pull-request-templates

Update GitHub issue templates to the new format

---

composer.json
tests/ExampleTest.php

Update the namespace for tests

---

.editorconfig
.travis.yml

Add a YAML indent of 2 spaces, and reorder the options alphabetically.

Add YAML indent size to EditorConfig

---

.github/workflows/ci.yml
README.md
phpunit.xml.dist

This updates the CI to use PCOV instead of Xdebug for code coverage.

Update to use PCOV for code coverage

---

README.md

Update the Build Status badge to use GitHub Actions.

Update Travis badge to GitHub Actions

---

.github/workflows/ci.yml
composer.json
phpstan.neon.dist

Add [PHPStan](https://github.com/phpstan/phpstan) for code analysis with Level 8.

Add PHPStan for analysis

---

.github/CONTRIBUTING.md
CHANGELOG.md
README.md
composer.json
phpunit.xml.dist
prefill.php
src/Skeleton.php
tests/ExampleTest.php

Update references to 'pxgamer'

---

.github/workflows/ci.yml

Update Cache action to v2

---

.github/workflows/ci.yml
composer.json
tests/ExampleTest.php

Update the default test runner to Pest.

Update to use Pest by default

---

composer.json
phpstan.neon.dist

See https://getcomposer.org/doc/04-schema.md#psr-4

Show the reader they are directories in Composer

---

.github/workflows/ci.yml
composer.json

Update to use Composer v2 for GitHub Actions

---

composer.json

Update to use Pest ^0.2

---

composer.json

Add var-dumper for dump/dd

---

composer.json

Rename Composer scripts for testing

---

.github/workflows/ci.yml
README.md

ci: remove CodeCov action

---

.github/workflows/static.yml
composer.json
rector.yaml

Add Rector for code updates

---

composer.json
phpunit.xml.dist

...
Please check the **[CONTRIBUTING](https://github.com/owenvoke/.github/blob/main/CONTRIBUTING.md)** document for more information.

chore(deps-dev): update Composer dependencies

---

.github/workflows/static.yml
.github/workflows/tests.yml

...
Please check the **[CONTRIBUTING](https://github.com/owenvoke/.github/blob/main/CONTRIBUTING.md)** document for more information.

chore: update GitHub Actions dependencies

---

composer.json

...
Please check the **[CONTRIBUTING](https://github.com/owenvoke/.github/blob/main/CONTRIBUTING.md)** document for more information.

chore(deps-dev): update to Pest 4.x

---

CHANGELOG.md
README.md

...
Please check the **[CONTRIBUTING](https://github.com/owenvoke/.github/blob/main/CONTRIBUTING.md)** document for more information.

docs: migrate to GitHub Releases for changelog
